---
AllCops:
  Exclude:
  - Gemfile
  - Rakefile
  - 'test/**/*'
  - 'vendor/**/*'
Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 11
Metrics/AbcSize:
  Max: 33
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Style/AlignHash:
  Enabled: false
Style/PredicateName:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Style/FileName:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NegatedIf:
  Enabled: false
Style/UnlessElse:
  Enabled: false
BlockDelimiters:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
